apiVersion: v1
kind: Pod
metadata: 
  name: greeter
  labels:
    plan: dev
spec:
  containers:
    - name: greeter
      image: jialtang/greeter:v1.0.0
      imagePullPolicy: Never
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 2001